Repository Capstone-AdCanvas/backend, pull requests merged in 2025-05, with the labels that each got.

#57 [feat] tts 변환 기능
  src/main/java/hello/backend/config/WebClientConfig.java
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/TTSRequest.java
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 🚀 Feat

#58 [feat] mp4 음향 설정 추가 기능 구현 (feat. mp3)
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/hello/backend/audio/Controller/AudioController.java
  src/main/java/hello/backend/audio/dto/AudioRequest.java
  src/main/java/hello/backend/audio/dto/AudioResponse.java
  src/main/java/hello/backend/audio/dto/AudioSaveResponse.java
  src/main/java/hello/backend/audio/service/AudioService.java
  src/main/java/hello/backend/config/FFmpegConfig.java
  src/main/java/hello/backend/config/FFmpegProperties.java
  src/main/resources/static/mp3/Forest.mp3
  src/main/resources/static/mp3/Wave.mp3
  src/main/resources/static/mp3/water.mp3
Labels: 🚀 Feat

#60 [refactor] tts text deepseek 연결
  docker-compose.yml
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 💻 Refactoring

#62 [refactor] tts option 추가
  .gitignore
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/tts/dto/TTSRequest.java
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 💻 Refactoring

#64 [feat] 로고 이미지 업로드, 조회
  .gitignore
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/controller/ImageLogoController.java
  src/main/java/hello/backend/image/domain/Logo.java
  src/main/java/hello/backend/image/dto/LogoResponse.java
  src/main/java/hello/backend/image/repository/LogoRepository.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageLogoService.java
Labels: 🚀 Feat

#66 [feat] TTS 모델 조회
  src/main/java/hello/backend/config/WebConfig.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/TTSResponse.java
  src/main/java/hello/backend/tts/dto/enums/TTSModel.java
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 🚀 Feat

#81 Google Cloud Storage 기능 구현
  .gitignore
  build.gradle
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/gcs/config/GcpConfig.java
  src/main/java/hello/backend/gcs/service/GCSService.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/TTSRequest.java
  src/main/java/hello/backend/tts/service/TTSService.java
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/domain/Video.java
  src/main/java/hello/backend/video/repository/VideoRepository.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 🚀 Feat

#84 [feat] 이미지 합성
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/dto/CombineImageRequest.java
  src/main/java/hello/backend/image/dto/CombineImageResponse.java
  src/main/java/hello/backend/image/dto/OverlayItemRequest.java
  src/main/java/hello/backend/image/repository/ImageRepository.java
  src/main/java/hello/backend/image/service/ImageService.java
Labels: 🚀 Feat

#86 [refactor] 영상합성 + 배경,효과음 통합 리팩토링
  src/main/java/hello/backend/audio/Controller/MergeController.java
  src/main/java/hello/backend/audio/dto/AudioRequest.java
  src/main/java/hello/backend/audio/dto/AudioResponse.java
  src/main/java/hello/backend/audio/dto/AudioSaveResponse.java
  src/main/java/hello/backend/audio/service/MergeService.java
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 💻 Refactoring

#87 [Refactor] 이미지 코드 GCS 설정
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/gcs/service/GCSService.java
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/controller/ImageLogoController.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/image/service/ImageFileService.java
  src/main/java/hello/backend/image/service/ImageLogoService.java
  src/main/java/hello/backend/image/service/ImageService.java
Labels: 💻 Refactoring

#89 [Feat] 비디오 조회
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/dto/VideoResponse.java
  src/main/java/hello/backend/video/repository/VideoRepository.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 🚀 Feat

#92 [feat] gcs cors 파일 업데이트
  src/main/java/hello/backend/config/cors-config.json
Labels: 🧭 Chore, 🚀 Feat

#93 [Refactor] 이미지, tts 수정
  .gitignore
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/config/WebConfig.java
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/domain/Image.java
  src/main/java/hello/backend/image/domain/Logo.java
  src/main/java/hello/backend/image/dto/ImageResponse.java
  src/main/java/hello/backend/image/dto/LogoResponse.java
  src/main/java/hello/backend/image/repository/ImageRepository.java
  src/main/java/hello/backend/image/service/ImageLogoService.java
  src/main/java/hello/backend/image/service/ImageService.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/TTSModelResponse.java
  src/main/java/hello/backend/tts/dto/TTSResponse.java
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 💻 Refactoring

#95 [fix] tts 경로 오류 수정
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/tts/controller/TTSController.java
Labels: 🏷 Fix

#97 [feat] 이미지 이름 설정 추가
  src/main/java/hello/backend/gcs/service/GCSService.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/service/ImageService.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/enums/TTSModel.java
Labels: 🚀 Feat

#99 [feat] 영상합성 + TTS 대본 합성 기능 추가Feat/#98
  src/main/java/hello/backend/audio/Controller/MergeController.java
  src/main/java/hello/backend/audio/dto/MergeRequest.java
  src/main/java/hello/backend/audio/service/MergeService.java
  src/main/java/hello/backend/config/FalConfig.java
Labels: 🚀 Feat, 💻 Refactoring

#101 [feat] tts 미리듣기
  src/main/java/hello/backend/config/WebConfig.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/TTSPreviewRequest.java
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 🚀 Feat

#103 [refactor] TTS 반환값 수정
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/tts/controller/TTSController.java
  src/main/java/hello/backend/tts/dto/TTSResponse.java
  src/main/java/hello/backend/tts/service/TTSService.java
Labels: 💻 Refactoring

#105 [refactor] tts 프롬프트 수정
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
Labels: 💻 Refactoring

#109 [refactor] 이미지 합성 코드 수정
  src/main/java/hello/backend/gcs/service/GCSService.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/dto/ImageUploadResponse.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/image/service/ImageFileService.java
  src/main/java/hello/backend/image/service/ImageService.java
Labels: 💻 Refactoring

#111 [refactor] 로고 이미지 크기조정, video 저장 경로 설정
  .gitignore
  src/main/java/hello/backend/config/WebConfig.java
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/image/service/ImageFileService.java
  src/main/java/hello/backend/image/service/ImageLogoService.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 💻 Refactoring

#117 [refactor] 영상 합성 코드 수정
  src/main/java/hello/backend/audio/service/MergeService.java
Labels: 💻 Refactoring

#125 [chore] gcs 경로 설정 리팩토링
  Dockerfile
  src/main/java/hello/backend/gcs/config/GcpConfig.java
  src/main/resources/application-prod.yml
Labels: 🧭 Chore, 💻 Refactoring

#127 [refactor] logo 엔티티 수정
  src/main/java/hello/backend/image/domain/Logo.java
  src/main/java/hello/backend/image/dto/LogoResponse.java
  src/main/java/hello/backend/image/service/ImageLogoService.java
  temp_28ca0295-9b2f-45b8-8af8-c8924991e9d6/.gitignore
Labels: 💻 Refactoring

#131 [chore] 모니터링 설정
  .gitignore
  build.gradle
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 🧭 Chore
