Repository Capstone-AdCanvas/backend, pull requests merged in 2025-04, with the labels that each got.

#28 [feat] 영상 변환 기능 구현
  build.gradle
  docker-compose.yml
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/domain/FalConfig.java
  src/main/java/hello/backend/video/domain/Video.java
  src/main/java/hello/backend/video/dto/ImageToVideoRequest.java
  src/main/java/hello/backend/video/dto/ImageToVideoResponse.java
  src/main/java/hello/backend/video/dto/SaveRequest.java
  src/main/java/hello/backend/video/dto/SaveResponse.java
  src/main/java/hello/backend/video/dto/TextToVideoRequest.java
  src/main/java/hello/backend/video/dto/TextToVideoResponse.java
  src/main/java/hello/backend/video/repository/VideoRepository.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 🚀 Feat

#30 feat: 이미지 테마 추가 및 조회
  src/main/java/hello/backend/image/config/AdImageThemeInitializer.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/domain/AdImageTheme.java
  src/main/java/hello/backend/image/dto/ThemeResponse.java
  src/main/java/hello/backend/image/repository/AdImageThemeRepository.java
  src/main/java/hello/backend/image/service/AdImageThemeService.java
Labels: 🚀 Feat

#32 [refactor] 이미지 기능별 파일 분리
  src/main/java/hello/backend/image/config/ImageThemeInitializer.java
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/domain/Image.java
  src/main/java/hello/backend/image/domain/ImageTheme.java
  src/main/java/hello/backend/image/repository/AdImageRepository.java
  src/main/java/hello/backend/image/repository/AdImageThemeRepository.java
  src/main/java/hello/backend/image/repository/ImageRepository.java
  src/main/java/hello/backend/image/repository/ImageThemeRepository.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/image/service/ImageService.java
  src/main/java/hello/backend/image/service/ImageThemeService.java
Labels: 💻 Refactoring

#34 [feat] 이미지 사이즈 설정
  src/main/java/hello/backend/image/config/ImageThemeInitializer.java
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/domain/ImageTheme.java
  src/main/java/hello/backend/image/domain/enums/ImageSize.java
  src/main/java/hello/backend/image/domain/enums/ImageTheme.java
  src/main/java/hello/backend/image/dto/SizeResponse.java
  src/main/java/hello/backend/image/dto/ThemeResponse.java
  src/main/java/hello/backend/image/repository/ImageThemeRepository.java
  src/main/java/hello/backend/image/service/ImageSizeService.java
  src/main/java/hello/backend/image/service/ImageThemeService.java
Labels: 🚀 Feat, 💻 Refactoring

#36 [feat] 사용자 프롬프트 리라이팅 구현(DeepSeek 사용)
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/config/DeepSeekConfig.java
  src/main/java/hello/backend/config/FalConfig.java
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 🚀 Feat

#38 [feat] 이미지 배경 생성
  src/main/java/hello/backend/config/WebClientConfig.java
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/domain/Image.java
  src/main/java/hello/backend/image/dto/BgGenerateRequest.java
  src/main/java/hello/backend/image/dto/BgGenerateResponse.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageBgService.java
Labels: 🚀 Feat

#41 [feat] 이미지 배경 커스텀 생성
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/domain/Image.java
  src/main/java/hello/backend/image/dto/BgCustomGenerateRequest.java
  src/main/java/hello/backend/image/service/ImageBgService.java
Labels: 🚀 Feat

#43 [feat] 최종 이미지 선택
  src/main/java/hello/backend/image/controller/ImageBgController.java
  src/main/java/hello/backend/image/dto/FinalImageRequest.java
  src/main/java/hello/backend/image/dto/FinalImageResponse.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageBgService.java
Labels: 🚀 Feat

#45 [refactor] 이미지 파일 리팩토링
  src/main/java/hello/backend/config/WebClientConfig.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageBgService.java
Labels: 💻 Refactoring

#46 [refactor] Video 구현 리팩토링(feat.image-to-video)
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/error/exception/image/UnsupportedMediaTypeException.java
  src/main/java/hello/backend/error/exception/user/BadRequestException.java
  src/main/java/hello/backend/error/exception/user/InvalidFileException.java
  src/main/java/hello/backend/error/exception/user/NotFoundException.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/image/service/ImageService.java
  src/main/java/hello/backend/user/service/UserService.java
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/domain/Video.java
  src/main/java/hello/backend/video/dto/ImageToVideoRequest.java
  src/main/java/hello/backend/video/dto/ImageToVideoResponse.java
  src/main/java/hello/backend/video/dto/SaveResponse.java
  src/main/java/hello/backend/video/dto/TextToVideoResponse.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 💻 Refactoring

#48 [refactor] Video 구현 리팩토링(feat.text-to-video)
  build.gradle
  docker-compose.yml
  src/main/java/hello/backend/ai/deepseek/service/DeepSeekService.java
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/error/ErrorResponse.java
  src/main/java/hello/backend/error/GlobalExceptionHandler.java
  src/main/java/hello/backend/error/exception/BusinessException.java
  src/main/java/hello/backend/error/exception/user/BadRequestException.java
  src/main/java/hello/backend/error/exception/user/InvalidFileException.java
  src/main/java/hello/backend/error/exception/user/NotFoundException.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/user/controller/UserController.java
  src/main/java/hello/backend/user/domain/User.java
  src/main/java/hello/backend/user/service/UserService.java
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/dto/ImageToVideoResponse.java
  src/main/java/hello/backend/video/dto/TextToVideoResponse.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 💻 Refactoring

#50 [fix] userService error 수정
  src/main/java/hello/backend/user/service/UserService.java
  src/main/java/hello/backend/video/contoller/VideoController.java
Labels: 🏷 Fix

#52 [refactor] Video 비동기 큐 적용 리팩토링
  build.gradle
  docker-compose.yml
  src/main/java/hello/backend/config/CaffeineConfig.java
  src/main/java/hello/backend/video/contoller/VideoController.java
  src/main/java/hello/backend/video/dto/ImageToVideoResponse.java
  src/main/java/hello/backend/video/dto/SubmitQueueResponse.java
  src/main/java/hello/backend/video/dto/TextToVideoResponse.java
  src/main/java/hello/backend/video/service/VideoService.java
Labels: 🧭 Chore, 🏷 Fix, 💻 Refactoring

#54 [Refactor] 이미지 예외처리, api 수정
  src/main/java/hello/backend/error/ErrorCode.java
  src/main/java/hello/backend/error/exception/image/UnsupportedMediaTypeException.java
  src/main/java/hello/backend/image/dto/ImageResponse.java
  src/main/java/hello/backend/image/service/FileStorageService.java
  src/main/java/hello/backend/image/service/ImageBgService.java
  src/main/java/hello/backend/image/service/ImageService.java
Labels: 💻 Refactoring
