Repository Capstone-AdCanvas/backend, pull requests merged in 2025-03, with the labels that each got.

#4 [chore] Swagger 세팅 완료
  build.gradle
  docker-compose.yml
  src/main/java/hello/backend/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: 🧭 Chore

#6 [feat] 회원가입 api 구현
  src/main/java/hello/backend/controller/UserController.java
  src/main/java/hello/backend/domain/User.java
  src/main/java/hello/backend/dto/UserRegisterRequest.java
  src/main/java/hello/backend/exception/BadRequestException.java
  src/main/java/hello/backend/repository/UserRepository.java
  src/main/java/hello/backend/service/UserService.java
  src/test/java/hello/backend/service/UserServiceTest.java
Labels: 🚀 Feat

#8 [feat] 회원정보 api 기능 구현 완료
  src/main/java/hello/backend/BackendApplication.java
  src/main/java/hello/backend/controller/UserController.java
  src/main/java/hello/backend/service/UserService.java
  src/main/java/hello/backend/user/controller/UserController.java
  src/main/java/hello/backend/user/domain/User.java
  src/main/java/hello/backend/user/dto/UserRegisterRequest.java
  src/main/java/hello/backend/user/dto/UserUpdateRequest.java
  src/main/java/hello/backend/user/exception/BadRequestException.java
  src/main/java/hello/backend/user/exception/NotFoundException.java
  src/main/java/hello/backend/user/repository/UserRepository.java
  src/main/java/hello/backend/user/service/UserService.java
Labels: 🚀 Feat

#12 [chore] 데이터베이스 연결 설정
  .gitignore
  src/main/resources/application.properties
Labels: 🧭 Chore

#14 [chore] jenkinsfile 설정
  Jenkinsfile
Labels: 🧭 Chore

#16 [Fix] Jenkinsfile 로직 수정
  Jenkinsfile
  src/main/java/hello/backend/user/controller/UserController.java
Labels: 🏷 Fix

#20 [feat] 이미지 업로드
  .gitignore
  src/main/java/hello/backend/exception/BadRequestException.java
  src/main/java/hello/backend/exception/NotFoundException.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/domain/AdImage.java
  src/main/java/hello/backend/image/dto/ImageResponse.java
  src/main/java/hello/backend/image/repository/AdImageRepository.java
  src/main/java/hello/backend/image/service/AdImageService.java
  src/main/java/hello/backend/user/service/UserService.java
  src/main/resources/.gitkeep
Labels: 🚀 Feat

#22 [refactor] 이미지 업로드 리팩토링
  src/main/java/hello/backend/exception/InvalidFileException.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/domain/AdImage.java
  src/main/java/hello/backend/image/dto/ImageResponse.java
  src/main/java/hello/backend/image/service/AdImageService.java
Labels: 💻 Refactoring

#24 [feat] 이미지 조회
  src/main/java/hello/backend/exception/UnsupportedMediaTypeException.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/repository/AdImageRepository.java
  src/main/java/hello/backend/image/service/AdImageService.java
  src/main/java/hello/backend/image/service/FileStorageService.java
Labels: 🚀 Feat

#27 [feat] 이미지 배경 제거
  build.gradle
  docker-compose.yml
  src/main/java/hello/backend/config/WebClientConfig.java
  src/main/java/hello/backend/image/controller/ImageController.java
  src/main/java/hello/backend/image/dto/BgRemoveResponse.java
  src/main/java/hello/backend/image/service/AdImageService.java
  src/main/java/hello/backend/image/service/FileStorageService.java
Labels: 🚀 Feat
